"""Differential data for Color.downgrade: color/downgrade_data_test.mbt."""
from pathlib import Path
from rich.color import Color, ColorSystem

rows = []
for r in range(0, 256, 15):
    for g in range(0, 256, 15):
        for b in range(0, 256, 15):
            c = Color.parse(f"#{r:02x}{g:02x}{b:02x}")
            rows.append((r, g, b, c.downgrade(ColorSystem.EIGHT_BIT).number,
                         c.downgrade(ColorSystem.STANDARD).number,
                         c.downgrade(ColorSystem.WINDOWS).number))
eight = []
for n in range(256):
    c = Color.from_ansi(n)
    eight.append((n, c.downgrade(ColorSystem.STANDARD).number, c.downgrade(ColorSystem.WINDOWS).number))
out = ["// Generated by scripts/color_oracle.py. DO NOT EDIT.", "", "///|",
       "let truecolor_downgrades : Array[(Int, Int, Int, Int, Int, Int)] = ["]
out += [f"  {row}," for row in rows]
out += ["]", "", "///|", "let eight_bit_downgrades : Array[(Int, Int, Int)] = ["]
out += [f"  {row}," for row in eight]
out += ["]", "", """///|
test "downgrade matches Python" {
  for row in truecolor_downgrades {
    let (r, g, b, eight, standard, windows) = row
    let c = @color.Color::from_triplet(@color.ColorTriplet::new(r, g, b))
    assert_eq(c.downgrade(EightBit).number, Some(eight))
    assert_eq(c.downgrade(Standard).number, Some(standard))
    assert_eq(c.downgrade(Windows).number, Some(windows))
  }
  for row in eight_bit_downgrades {
    let (n, standard, windows) = row
    let c = @color.Color::from_ansi(n)
    assert_eq(c.downgrade(Standard).number, Some(standard))
    assert_eq(c.downgrade(Windows).number, Some(windows))
  }
}"""]
Path(__file__).parent.parent.joinpath("color/downgrade_data_test.mbt").write_text("\n".join(out) + "\n")
