"""Generate color/gen_data.mbt from rich.color, rich._palettes, rich.terminal_theme."""
from pathlib import Path

from rich import _palettes, terminal_theme
from rich.color import ANSI_COLOR_NAMES

out = ["// Generated by scripts/gen_color.py. DO NOT EDIT.", ""]


def palette(name, pal):
    out.append("///|")
    out.append(f"pub let {name} : Palette = Palette::new([")
    for c in pal._colors:
        out.append(f"  ({c[0]}, {c[1]}, {c[2]}),")
    out.append("])")
    out.append("")


palette("windows_palette", _palettes.WINDOWS_PALETTE)
palette("standard_palette", _palettes.STANDARD_PALETTE)
palette("eight_bit_palette", _palettes.EIGHT_BIT_PALETTE)

for name in ["DEFAULT_TERMINAL_THEME", "MONOKAI", "DIMMED_MONOKAI", "NIGHT_OWLISH", "SVG_EXPORT_THEME"]:
    t = getattr(terminal_theme, name)
    bg = tuple(t.background_color)
    fg = tuple(t.foreground_color)
    colors = [tuple(c) for c in t.ansi_colors._colors]
    out.append("///|")
    out.append(f"pub let {name.lower()} : TerminalTheme = TerminalTheme::new(")
    out.append(f"  {bg},")
    out.append(f"  {fg},")
    out.append("  [" + ", ".join(str(tuple(c)) for c in colors[:8]) + "],")
    out.append("  bright=[" + ", ".join(str(tuple(c)) for c in colors[8:]) + "],")
    out.append(")")
    out.append("")

out.append("///|")
out.append("let ansi_color_names : Map[String, Int] = {")
for k, v in ANSI_COLOR_NAMES.items():
    out.append(f'  "{k}": {v},')
out.append("}")
out.append("")
out.append("///|")
out.append("/// All named colors (as accepted by `Color::parse`) and their numbers, in")
out.append("/// upstream order.")
out.append("pub fn ansi_color_name_list() -> Array[(String, Int)] {")
out.append("  ansi_color_names.to_array()")
out.append("}")
Path(__file__).parent.parent.joinpath("color/gen_data.mbt").write_text("\n".join(out) + "\n")
