"""Generate differential markup / literal_eval tests from the Python oracle.

Run with the oracle venv from the repository root:

    /path/to/.venv/bin/python scripts/gen_markup_tests.py

Writes `markup_oracle_test.mbt` (black-box) and `literal_eval_wbtest.mbt`
(white-box). Span offsets are converted to UTF-16 offsets.
"""
import os
from ast import literal_eval

from rich.errors import MarkupError
from rich.markup import escape, render
from rich.style import Style

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = "// Generated by scripts/gen_markup_tests.py from the Python oracle."


def mbt_str(s: str) -> str:
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def delist(v):
    if isinstance(v, (tuple, list)):
        return [delist(x) for x in v]
    if isinstance(v, dict):
        return {k: delist(x) for k, x in v.items()}
    return v


def u16(plain: str, offset: int) -> int:
    return len(plain[:offset].encode("utf-16-le")) // 2


def span_repr(plain, span):
    style = span.style
    start, end = u16(plain, span.start), u16(plain, span.end)
    if isinstance(style, Style):
        return f"Span({start}, {end}, meta={delist(style.meta)!r})"
    return f"Span({start}, {end}, {style!r})"


def text_repr(t):
    spans = ", ".join(span_repr(t.plain, s) for s in t.spans)
    return f"<text {t.plain!r} [{spans}] {t.style!r}>"


MARKUP_CASES = [
    "foo[/]", "foo[/bar]", "[foo]hello[/bar]",
    "[@click=sdfwer(sfs)]foo[/]", "[@click='view.toggle]foo[/]",
    "[bold red]Hello[/] [italic]World",
    "[b]a[i]b[/b]c[/i]d",
    "[link=https://example.org]x[/link]",
    "[link https://example.org]x[/]",
    "[bold]\\[not a tag][/bold]",
    "[ bold ]x[/ bold ]",
    "[BOLD]x[/bold]",
    "[bold italic]x[/italic bold]",
    "[red on blue]x[/red on blue]",
    "[#ff0000]x[/]",
    "[@foo ]x[/@foo]",
    "[@foo\u3000]x[/@foo]",
    "[@foo=1]x[/@foo]",
    "[@foo=1.5]x[/@foo]",
    "[@foo=[1, 2]]x[/@foo]",
    "[@foo={'a': 1}]x[/@foo]",
    "[@foo=None]x[/@foo]",
    "[@foo=True, False]x[/@foo]",
    "[@foo=a.b(1, 'x', None)]x[/@foo]",
    "[@foo=a.b()]x[/@foo]",
    "[@foo=()]x[/@foo]",
    "[@foo='it''s']x[/@foo]",
    "[@foo=\"q\"]x[/@foo]",
    "[@foo=-3]x[/@foo]",
    "[@foo=0x1F]x[/@foo]",
    "[@foo=1e3]x[/@foo]",
    "[@foo=(1,)]x[/@foo]",
    "[@foo=bar baz]x[/@foo]",
    "[@foo=)]x[/@foo]",
    "[@foo=(]x[/@foo]",
    "[@foo='a', ('b', -2.5)]x[/@foo]",
    "[@foo=f(x)]x[/@foo]",
    "[@foo=f(1,2]x[/@foo]",
    "[@foo= ]x[/@foo]",
    "[@foo=]x[/@foo]",
    "[@foo=1+2]x[/@foo]",
    "[@foo=--3]x[/@foo]",
    "[@foo={1: 'a', 'b': [1, 2]}]x[/@foo]",
    "[@foo={1:}]x[/@foo]",
    "[@foo='\\n\\t\\x41\\u00e9']x[/@foo]",
    "[@foo=007]x[/@foo]",
    "[@foo=(1]x[/@foo]",
    "[@]x[/@]",
    "[red]unclosed",
    "[red][green]a[/red]b",
    "x[/]y",
    ":smile: [bold]:thumbs_up:[/bold]",
    ":smile:",
    "\\\\\\\\[b]x",
    "[a=b=c]x[/a]",
    "[]x",
    "[1]x[/1]",
    "[/ ]x",
    "a[b]c[/b][/b]",
    "[i][b][/i][/b]",
    "[dim]x[/not dim]",
    "[not bold]x[/not bold]",
    "[foo-bar]x[/foo-bar]",
    "[red]a[/]b[/]",
    "[red]a\\[b\\]c[/red]",
    "[red]\\\\[/red]",
    "[red]a\\\\\\[/red]b",
    "no tags \\[at all]",
    "[bold]你好[/bold] 世界",
    "[bold]😀[italic]😀[/bold]😀",
    "[red]a[blue]b[green]c[/blue]d[/]e[/red]",
    "[link=https://a.b/?q=[1]]x[/link]",
    "[on red]x[/on red]",
    "[color(1)]x[/color(1)]",
    "[rgb(1,2,3)]x[/]",
]

ESCAPE_CASES = [
    "foo[bar]", "a\\", "a\\\\", "[x][y]", "[[a]]", "\\[a]", "[@x]", "[#ab]",
    "C:\\path\\", "[a] [/b] [c=d]", "[5]", "x[1]y", "[A]", "[a b]", "\\\\[a]", "[a",
]

LITERAL_CASES = [
    "", "(", "(1", "[1", "1 2", ")", "a b", "'x", "'''x", "{1:}", "(1]", "sfs", "x.y",
    "f(1)", "1+2", "-x", "{1, 2}", "b'x'", "[1,,2]", "(,)", "'a\\x41'", "'\\u00e9'",
    "r'\\n'", "u'x'", "1_000", "0o17", "0b11", ".5", "1.", "00", "007", "-0x10", "+3",
    "--3", "True, False", "1,", ",", "x)", "[1](", " (1, 2) ", "{'a': [1, (2,)]}",
    "{1: 2}", "{'a': None, 'b': True}", "'a' 'b'", "\"x\\\"y\"", "set()", "[]", "{}",
    "(((1)))", "1e-3", "-2.5", "[1, 'two', 3.5]", "'''a\nb'''", "1 + 'a'", "'a' + 1",
    "{1: 2, 3: 4,}", "(1, 2,)", "1*2", "2**3", "~1", "'\\101'",
]


def markup_tests():
    lines = [HEADER, "", "///|", 'test "markup oracle cases" {']
    lines.append("  let cases : Array[(String, String)] = [")
    for c in MARKUP_CASES:
        try:
            out = text_repr(render(c))
        except MarkupError as e:
            out = "MarkupError: " + str(e)
        lines.append(f"    ({mbt_str(c)}, {mbt_str(out)}),")
    lines += ["  ]", "  for case in cases {", "    assert_eq(render_case(case.0), case.1)", "  }", "}", ""]
    lines += ["///|", 'test "escape oracle cases" {']
    lines.append("  let cases : Array[(String, String, String)] = [")
    for c in ESCAPE_CASES:
        escaped = escape(c)
        lines.append(f"    ({mbt_str(c)}, {mbt_str(escaped)}, {mbt_str(render(escaped).plain)}),")
    lines += [
        "  ]",
        "  for case in cases {",
        "    assert_eq(@rich.escape(case.0), case.1)",
        "    assert_eq(@rich.render_markup(case.1).plain(), case.2)",
        "  }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def literal_tests():
    lines = [HEADER, "", "///|", 'test "literal_eval oracle cases" {']
    lines.append("  let cases : Array[(String, String)] = [")
    for c in LITERAL_CASES:
        try:
            out = "OK " + repr(literal_eval(c))
        except SyntaxError as e:
            out = "SyntaxError " + e.msg
        except Exception as e:
            out = type(e).__name__ + " " + str(e)
        lines.append(f"    ({mbt_str(c)}, {mbt_str(out)}),")
    lines += ["  ]", "  for case in cases {", "    assert_eq(literal_eval_case(case.0), case.1)", "  }", "}"]
    return "\n".join(lines) + "\n"


with open(os.path.join(ROOT, "markup_oracle_test.mbt"), "w") as f:
    f.write(markup_tests())
with open(os.path.join(ROOT, "literal_eval_wbtest.mbt"), "w") as f:
    f.write(literal_tests())
