"""Generate default_styles_data.mbt from rich.default_styles."""
from pathlib import Path
from rich.default_styles import DEFAULT_STYLES
from rich.style import Style

out = ["// Generated by scripts/gen_default_styles.py. DO NOT EDIT.", ""]
out.append("///|")
out.append("let default_style_definitions : Array[(String, String)] = [")
for name, style in DEFAULT_STYLES.items():
    definition = str(style)
    assert Style.parse(definition) == style, (name, definition)
    out.append(f'  ("{name}", "{definition}"),')
out.append("]")
Path(__file__).parent.parent.joinpath("default_styles_data.mbt").write_text("\n".join(out) + "\n")
print(len(DEFAULT_STYLES))
