"""Generate cells/gen_tables.mbt from rich._unicode_data."""
import importlib
from pathlib import Path

from rich._unicode_data._versions import VERSIONS

out = ["// Generated by scripts/gen_cells.py from rich/_unicode_data. DO NOT EDIT.", ""]
out.append("///|")
out.append("let versions : Array[String] = [")
for v in VERSIONS:
    out.append(f'  "{v}",')
out.append("]")
out.append("")
for v in VERSIONS:
    mod = importlib.import_module("rich._unicode_data.unicode" + v.replace(".", "-"))
    t = mod.cell_table
    name = "table_" + v.replace(".", "_")
    flat = []
    for s, e, w in t.widths:
        flat.extend([s, e, w])
    out.append("///|")
    out.append(f"let {name}_widths : FixedArray[Int] = [")
    for i in range(0, len(flat), 12):
        out.append("  " + ", ".join(str(x) for x in flat[i : i + 12]) + ",")
    out.append("]")
    out.append("")
    out.append("///|")
    out.append(f"let {name}_narrow_to_wide : FixedArray[Int] = [")
    cps = sorted(ord(c) for c in t.narrow_to_wide)
    for i in range(0, len(cps), 12):
        out.append("  " + ", ".join(str(x) for x in cps[i : i + 12]) + ",")
    out.append("]")
    out.append("")
out.append("///|")
out.append("fn raw_table(version : String) -> (FixedArray[Int], FixedArray[Int]) {")
out.append("  match version {")
for v in VERSIONS:
    name = "table_" + v.replace(".", "_")
    out.append(f'    "{v}" => ({name}_widths, {name}_narrow_to_wide)')
out.append("    _ => abort(\"unknown unicode version \" + version)")
out.append("  }")
out.append("}")
Path(__file__).parent.parent.joinpath("cells/gen_tables.mbt").write_text("\n".join(out) + "\n")
