"""Extract the expected strings of upstream tests/test_syntax.py into
syntax/upstream_expected_test.mbt (one `let expected_<test>` per test).

Some upstream expectations predate Pygments 2.19, which changed the monokai
style (e.g. `Name.Builtin` is now green). For tests that fail against the
installed Pygments (2.21, the version bobzhang/pygments ports), the expected
string is the oracle's actual output instead (captured by wrapping the test
module's `render`), and the generated file says so.

Run with the oracle Python from the worktree root:
    /Users/dii/git/rich.mbt/.venv/bin/python scripts/gen_syntax_expected.py
"""
import ast
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from mbt_literal import mbt_lines  # noqa: E402

TESTS = Path("/Users/dii/git/rich.mbt/.repos/rich/tests")
UPSTREAM = TESTS / "test_syntax.py"
OUT = Path(__file__).parent.parent / "syntax" / "upstream_expected_test.mbt"

sys.path.insert(0, str(TESTS.parent))
import tests.test_syntax as T  # noqa: E402

captured = []
_render = T.render


def recording_render(*args, **kwargs):
    result = _render(*args, **kwargs)
    captured.append(result)
    return result


T.render = recording_render

tree = ast.parse(UPSTREAM.read_text())
out = ["// Generated by scripts/gen_syntax_expected.py from upstream",
       "// tests/test_syntax.py. DO NOT EDIT.", ""]
for node in tree.body:
    if isinstance(node, ast.Assign) and node.targets[0].id == "CODE":
        out.append("///|")
        out.append(mbt_lines("code", node.value.value).rstrip())
        out.append("")
    if not isinstance(node, ast.FunctionDef):
        continue
    strings = [
        n.value
        for n in ast.walk(node)
        if isinstance(n, ast.Constant) and isinstance(n.value, str)
    ]
    doc = ast.get_docstring(node, clean=False)
    long = [s for s in strings if ("\x1b" in s or len(s) > 40) and s != doc]
    if not long:
        continue
    expected = max(long, key=len)
    name = node.name.removeprefix("test_")
    captured.clear()
    try:
        getattr(T, node.name)()
    except AssertionError:
        assert len(captured) == 1, node.name
        expected = captured[0]
        out.append(f"// Upstream expectation is for an older Pygments; this is the")
        out.append(f"// output of upstream Rich with Pygments 2.21.")
    out.append("///|")
    out.append(mbt_lines(f"expected_{name}", expected).rstrip())
    out.append("")
OUT.write_text("\n".join(out))
print(f"wrote {OUT}")
