"""Generate spinner/gen_spinners.mbt from rich._spinners."""
from pathlib import Path
from rich._spinners import SPINNERS

out = ["// Generated by scripts/gen_spinners.py from rich/_spinners.py. DO NOT EDIT.", ""]


def lit(s):
    r = []
    for c in s:
        o = ord(c)
        if c in '"\\':
            r.append("\\" + c)
        elif o < 0x20 or 0x7f <= o < 0xa0 or 0x200b <= o <= 0x200f or 0xfe00 <= o <= 0xfe0f or 0xe0000 <= o:
            r.append("\\u{%x}" % o)
        else:
            r.append(c)
    return '"' + "".join(r) + '"'


out.append("///|")
out.append("/// Spinner animations: name -> (interval in milliseconds, frames).")
out.append("/// Frames given upstream as a string are split into code points.")
out.append("let spinners : Map[String, (Double, Array[String])] = {")
for name, spinner in SPINNERS.items():
    frames = list(spinner["frames"])
    interval = spinner["interval"]
    frames_lit = ", ".join(lit(f) for f in frames)
    out.append(f"  {lit(name)}: ({float(interval)!r}, [{frames_lit}]),")
out.append("}")
Path(__file__).parent.parent.joinpath("spinner/gen_spinners.mbt").write_text(
    "\n".join(out) + "\n"
)
