"""Generate emoji/gen_codes.mbt from rich._emoji_codes."""
import json
from pathlib import Path
from rich._emoji_codes import EMOJI

out = ["// Generated by scripts/gen_emoji.py from rich/_emoji_codes.py. DO NOT EDIT.", ""]
out.append("///|")
out.append("let emoji_codes : Map[String, String] = {")
def lit(s):
    r = []
    for c in s:
        o = ord(c)
        if c in '"\\':
            r.append("\\" + c)
        elif o < 0x20 or 0x7f <= o < 0xa0 or 0x200b <= o <= 0x200f or 0xfe00 <= o <= 0xfe0f or 0xe0000 <= o:
            r.append("\\u{%x}" % o)
        else:
            r.append(c)
    return '"' + "".join(r) + '"'


for k, v in EMOJI.items():
    out.append(f"  {lit(k)}: {lit(v)},")
out.append("}")
Path(__file__).parent.parent.joinpath("emoji/gen_codes.mbt").write_text("\n".join(out) + "\n")
