"""Differential tests for Console.log: writes `log_oracle_test.mbt`.

The MoonBit source is generated first so that the line numbers of the
`console.log` calls are known; upstream's caller frame lookup is patched to
report them, and times are fixed with `get_datetime`.

    /Users/dii/git/rich.mbt/.venv/bin/python scripts/log_oracle.py
"""
import io
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from unittest import mock

from rich.console import Console
from rich.table import Table

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "log_oracle_test.mbt"
FILENAME = "log_oracle_test.mbt"
T0 = 1700000000.0  # 2023-11-14 22:13:20 UTC
T1 = 1700003723.0  # 2023-11-14 23:15:23 UTC


def normalize(s):
    """Replace the random ids of hyperlinks."""
    return re.sub(r"id=\d+;", "id=0;", s)


def mbt_str(s: str) -> str:
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif o < 0x20 or o == 0x7F:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


# A case: console kwargs (python, mbt), and a list of steps. A step is
# (time, python_call(console), mbt_call_line) where mbt_call_line must be a
# single line.
cases = []


def case(name, width, steps, py_kw=None, mbt_kw=None, color_system="truecolor"):
    cases.append((name, width, steps, py_kw or {}, mbt_kw or [], color_system))


def log(*objects, mbt_args=None, **kw):
    """A console.log step with string objects."""
    def py(console):
        console.log(*objects, **kw)

    objs = list(objects)
    if len(objs) == 1:
        args = [mbt_str(objs[0])]
        fn = "log"
    else:
        args = ["[" + ", ".join(mbt_str(o) for o in objs) + "]"]
        fn = "log_many"
    for k, v in kw.items():
        if isinstance(v, bool):
            args.append(f"{k}={'true' if v else 'false'}")
        elif k == "justify":
            args.append(f"justify={v.capitalize()}")
        else:
            args.append(f"{k}={mbt_str(v)}")
    if mbt_args:
        args.extend(mbt_args)
    return py, f"console.{fn}({', '.join(args)})"


def log_empty():
    def py(console):
        console.log()

    return py, "console.log_many([])"


def log_table():
    def py(console):
        table = Table("A", "B")
        table.add_row("1", "2")
        console.log(table)

    return py, "console.log(log_table())"


case("render_log", 80, [
    (T0, *log_empty()),
    (T0, *log("Hello from", "<console width=80 ColorSystem.TRUECOLOR>", "!")),
    (T0, *log("[1, 2, 3]")),
], py_kw={"log_time_format": "[TIME]"}, mbt_kw=['log_time_format="[TIME]"'])

case("default time format", 80, [
    (T0, *log("first")),
    (T0, *log("same time")),
    (T1, *log("later")),
    (T1, *log("again")),
])
case("time format date", 60, [
    (T0, *log("dated")),
], py_kw={"log_time_format": "%Y-%m-%d %H:%M:%S"},
    mbt_kw=['log_time_format="%Y-%m-%d %H:%M:%S"'])
case("no path", 50, [
    (T0, *log("message without path")),
], py_kw={"log_path": False}, mbt_kw=["log_path=false"])
case("no time", 50, [
    (T0, *log("message without time")),
], py_kw={"log_time": False}, mbt_kw=["log_time=false"])
case("no time no path", 30, [
    (T0, *log("foo", justify="right")),
    (T0, *log("bar", justify="center")),
], py_kw={"log_time": False, "log_path": False},
    mbt_kw=["log_time=false", "log_path=false"])
case("justify with path", 60, [
    (T0, *log("right", justify="right")),
    (T0, *log("center", justify="center")),
    (T0, *log("left", justify="left")),
])
case("wrapping", 40, [
    (T0, *log("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do "
              "eiusmod tempor incididunt ut labore")),
    (T0, *log("Averyveryveryveryveryverylongwordthatmustfold")),
])
case("style and markup", 60, [
    (T0, *log("[bold]bold[/] text", style="on blue")),
    (T0, *log("[bold]not markup", markup=False)),
    (T0, *log(":smile: 123", emoji=False, highlight=False)),
    (T1, *log("a", "b", "c", sep="-")),
])
case("renderable", 50, [
    (T0, *log_table()),
    (T0, *log("after table")),
])
case("no color", 50, [
    (T0, *log("plain 123")),
], color_system=None)


def mbt_console(width, mbt_kw, color_system):
    cs = "None" if color_system is None else f'Some("{color_system}")'
    args = ["file~", f"width={width}", "force_terminal=true",
            f"color_system={cs}", "legacy_windows=false", "environ={}",
            "get_datetime=() => now.val"] + mbt_kw
    return f"  let console = @rich.Console::new({', '.join(args)})"


lines = [
    "// Generated by scripts/log_oracle.py from upstream Rich. DO NOT EDIT.",
    "",
    "///|",
    "fn log_table() -> @rich.Table raise {",
    '  let table = @rich.Table::new(headers=["A", "B"])',
    '  table.add_row(["1", "2"])',
    "  table",
    "}",
    "",
    "///|",
    "/// Compare with the expected output of case `index` (times are rendered",
    "/// in UTC by the oracle and in local time here; link ids are random).",
    "fn check_log(output : String, index : Int) -> Unit raise {",
    "  let (expected, fmt, times) = log_expected[index]",
    "  let expected = replace_times(",
    "    expected,",
    "    times.map(t => (t.0, @term.strftime(fmt, t.1))),",
    "  )",
    "  assert_eq(normalize_link_ids(output), expected)",
    "}",
    "",
]
for index, (name, width, steps, py_kw, mbt_kw, color_system) in enumerate(cases):
    lines.append("///|")
    lines.append(f"test {mbt_str('log oracle ' + name)} {{")
    lines.append("  let file = @rich.StringIO::new()")
    lines.append(f"  let now = Ref({steps[0][0]})")
    lines.append(mbt_console(width, mbt_kw, color_system))
    for t, py, mbt in steps:
        lines.append(f"  now.val = {t}")
        lines.append(f"  {mbt}")
    lines.append(f"  check_log(file.getvalue(), {index})")
    lines.append("}")
    lines.append("")
lines.append("///|")
lines.append("let log_expected : Array[(String, String, Array[(String, Double)])] = []")

# pass 1: format, then find the line numbers of the log calls
OUT.write_text("\n".join(lines) + "\n")
subprocess.run(["moon", "fmt"], cwd=ROOT, check=True, capture_output=True)
formatted = OUT.read_text().split("\n")
call_lines = []  # per test
for i, line in enumerate(formatted, start=1):
    if line.startswith("test "):
        call_lines.append([])
    elif "console.log" in line and call_lines:
        call_lines[-1].append(i)

data = []
for (name, width, steps, py_kw, mbt_kw, color_system), step_lines in zip(cases, call_lines):
    assert len(step_lines) == len(steps), name
    file = io.StringIO()
    now = [None]
    console = Console(
        file=file, width=width, force_terminal=True, color_system=color_system,
        legacy_windows=False, _environ={},
        get_datetime=lambda: now[0], **py_kw,
    )
    times = set()
    for (t, py, _), line_no in zip(steps, step_lines):
        now[0] = datetime.fromtimestamp(t, timezone.utc)
        times.add(t)
        with mock.patch.object(Console, "_caller_frame_info",
                               staticmethod(lambda offset, *a: (FILENAME, line_no, {}))), \
                mock.patch("rich.console.os.path.abspath", lambda p: p):
            py(console)
    fmt = py_kw.get("log_time_format", "[%X]")
    pairs = []
    if "%" in fmt:
        for t in sorted(times):
            utc = datetime.fromtimestamp(t, timezone.utc).strftime(fmt)
            pairs.append(f"({mbt_str(utc)}, {t})")
    data.append(f"  ({mbt_str(normalize(file.getvalue()))}, {mbt_str(fmt)}, [{', '.join(pairs)}]),")

# pass 2: the expected data goes at the end, so line numbers do not move
text = "\n".join(formatted)
text = text.replace(
    "let log_expected : Array[(String, String, Array[(String, Double)])] = []",
    "let log_expected : Array[(String, String, Array[(String, Double)])] = [\n"
    + "\n".join(data) + "\n]",
)
OUT.write_text(text)
subprocess.run(["moon", "fmt"], cwd=ROOT, check=True, capture_output=True)
print(f"wrote {len(cases)} cases to {OUT}")
