"""Random-document differential check of markdown/ against markdown-it-py.

Run with the Python oracle (upstream Rich + markdown-it-py):

    /Users/dii/git/rich.mbt/.venv/bin/python scripts/markdown_fuzz.py [N] [SEED]
    moon test markdown -F 'fuzz*' > fuzz.out
    rm markdown/fuzz_data_test.mbt

It generates N (default 5000) random documents from fragments that
exercise the adapter (tables, strikethrough, raw HTML, autolinks, link
references, containers, lazy lines, ...) and writes a temporary test,
`markdown/fuzz_data_test.mbt` (not committed), comparing `parse_tokens`
with markdown-it's flattened token stream. The test prints one
`FUZZ_FAIL <index>\t<actual dump>` line per mismatch and a summary line,
so the outputs of two versions of the adapter can be diffed.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from markdown_oracle import dump_tokens, mbt_str  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "markdown/fuzz_data_test.mbt"

BLOCK_PREFIXES = [
    "", "", "", "", "", "", "# ", "## ", "> ", "> > ", "- ", "* ", "+ ",
    "1. ", "2) ", "10. ", "  ", "   ", "    ", "\t", "  - ", "> - ", "- > ",
    "```", "~~~", "``` py", "---", "===", "***", "<div>", "</div>", "<pre>",
    "<!--", "-->", "<?php", "<foo>", "</a>", "[ref]: /url", "[Ref]: <u r l>",
    "[ẞ]: /sz 'title'", "[x]: /x\n", "|", ":-|-:", "|---|---|", "--|--",
    "-|", "| - |", ">",
]

INLINE = [
    "word", "foo", "bar", "baz", "a", "b", " ", "  ", " ", "\t", "*", "**",
    "***", "_", "__", "~", "~~", "~~~", "`", "``", "[", "]", "(", ")", "![",
    "<", ">", "<a", "<a href=\"x\">", "<b>", "</b>", "<kbd>", "</kbd>",
    "<!-- c -->", "<!--", "-->", "<!-->", "<!--->", "<http://a.b/c>",
    "<a@b.c>", "<javascript:x>", "<u r l>", "<?x?>", "<![CDATA[x]]>",
    "<!X y>", "\\", "\\*", "\\~", "\\|", "\\`", "\\\\", "&amp;", "&#35;",
    "&copy;", "&bogus;", "|", "|", "|", "é", "中", "😀", "ß", "ẞ", "[ref]",
    "[REF]", "[ẞ]", "[ss]", "[Ref][]", "[x][ref]", "(/url)", "(/u 't')",
    "(<a b>)", "(javascript:x)", "](/u)", "\"", "'", ".", "!", "?",
    "<foo bar=baz", "bim!bop />", "http://x.y", "\u00a0", "$", "1.",
]


def random_line(rng: random.Random) -> str:
    prefix = rng.choice(BLOCK_PREFIXES)
    if rng.random() < 0.15:
        prefix = rng.choice(BLOCK_PREFIXES) + prefix
    parts = [rng.choice(INLINE) for _ in range(rng.randint(0, 7))]
    if rng.random() < 0.2:
        # a table-looking row
        parts = [" | ".join(rng.choice(INLINE) for _ in range(rng.randint(1, 3)))]
        if rng.random() < 0.5:
            parts = ["| ", *parts, " |"]
    return prefix + "".join(parts)


def random_doc(rng: random.Random) -> str:
    lines = [random_line(rng) for _ in range(rng.randint(1, 8))]
    if rng.random() < 0.3:
        # a delimiter row after a random line makes tables likely
        k = rng.randrange(len(lines))
        lines.insert(k + 1, rng.choice(["|---|---|", "--|--", "| - |", ":-:|", "---"]))
    doc = "\n".join(lines)
    return doc + ("\n" if rng.random() < 0.7 else "")


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    rng = random.Random(seed)
    out = [
        "// Generated by scripts/markdown_fuzz.py. DO NOT COMMIT.",
        "",
        "///|",
        "let fuzz_token_cases : Array[(String, String)] = [",
    ]
    for _ in range(n):
        doc = random_doc(rng)
        out.append(f"  ({mbt_str(doc)}, {mbt_str(dump_tokens(doc))}),")
    out += [
        "]",
        "",
        "///|",
        'test "fuzz: markdown-it token stream" {',
        "  let mut failures = 0",
        "  for i, case in fuzz_token_cases {",
        "    let (markup, expected) = case",
        "    let actual = @markdown.parse_tokens(markup).map(t => t.dump()).join(\"\\n\")",
        "    if actual != expected {",
        "      failures += 1",
        '      println("FUZZ_FAIL \\{i}\\t\\{actual.escape()}")',
        "    }",
        "  }",
        '  println("FUZZ_SUMMARY \\{fuzz_token_cases.length() - failures}/\\{fuzz_token_cases.length()}")',
        "}",
    ]
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({n} documents, seed {seed})")


if __name__ == "__main__":
    main()
