"""Generate scope/scope_test.mbt: expected output of `render_scope` computed
by upstream Rich.

    /path/to/.venv/bin/python scripts/scope_oracle.py > scope/scope_test.mbt && moon fmt
"""

import io

from rich.console import Console
from rich.scope import render_scope


def mbt_str(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def render(scope, width, color, **kwargs):
    f = io.StringIO()
    console = Console(
        file=f,
        width=width,
        color_system="truecolor" if color else None,
        force_terminal=color,
        legacy_windows=False,
        _environ={},
    )
    console.print(render_scope(scope, **kwargs))
    return f.getvalue()


demo = {
    "foo": 20.3423,
    "bar": 3.1427,
    "list_of_things": [1, 2, 3, None, 4, True, False, "Hello World"],
    "dict_of_things": {
        "version": "1.1",
        "method": "confirmFruitPurchase",
        "params": [["apple", "orange", "mangoes", "pomelo"], 1.123],
        "id": "194521489",
    },
}
special = {
    "zebra": 1,
    "Apple": "a",
    "__name__": "__main__",
    "apple": "b",
    "__doc__": None,
    "_private": [1, 2],
    "Zed": {"k": "v"},
}

# (name, python scope, MoonBit scope expression, width, color, kwargs, mbt kwargs)
CASES = [
    ("demo unsorted", demo, "demo_scope()", 80, True, dict(title="[i]locals", sort_keys=False), 'title="[i]locals", sort_keys=false'),
    ("demo sorted", demo, "demo_scope()", 80, False, dict(), ""),
    ("demo narrow", demo, "demo_scope()", 40, True, dict(indent_guides=True), "indent_guides=true"),
    ("demo max_length", demo, "demo_scope()", 60, False, dict(max_length=2, max_string=4), "max_length=2, max_string=4"),
    ("demo max_depth", demo, "demo_scope()", 60, False, dict(max_depth=1, title="Scope"), 'max_depth=1, title="Scope"'),
    ("special keys", special, "special_scope()", 50, True, dict(), ""),
    ("special keys unsorted", special, "special_scope()", 50, False, dict(sort_keys=False), "sort_keys=false"),
    ("overflow", {"s": "x" * 60}, 'long_scope()', 30, False, dict(overflow="ellipsis"), "overflow=Ellipsis"),
]

print("// Generated by scripts/scope_oracle.py from upstream Rich; do not edit.")
for name, scope, expr, width, color, kwargs, mbt_kwargs in CASES:
    expected = render(scope, width, color, **kwargs)
    args = f", {mbt_kwargs}" if mbt_kwargs else ""
    print()
    print("///|")
    print(f'test "{name}" {{')
    print(
        f"  assert_eq(render({expr}, width={width}, color={str(color).lower()}{args}), {mbt_str(expected)})"
    )
    print("}")
